Repository wecode-bootcamp-korea/46-1st-WePet-backend, pull requests merged in 2023-06, with the labels that each got.

#2 :triangular_flag_on_post: [ADD]: get request for products
  app.js
  controllers/index.js
  controllers/productsController.js
  db/migrations/20230531120341_alter_products_table.sql
  db/migrations/20230601050150_create_extra_product_images_table.sql
  db/migrations/20230601053106_alter_products_table.sql
  db/migrations/20230601053809_alter_users_table.sql
  models/productsDao.js
  routers/index.js
  routers/productRouter.js
  routers/productsRouter.js
  routers/userRouter.js
  routers/usersRouter.js
  services/index.js
  services/productsService.js
  utils/errorHandler.js
Labels: 멘토 리뷰 요청

#7 Feature/auths
  app.js
  controllers/index.js
  controllers/productsController.js
  controllers/usersController.js
  models/addressDao.js
  models/usersDao.js
  models/usersPaymentDao.js
  routers/index.js
  routers/productsRouter.js
  routers/usersRouter.js
  services/index.js
  services/productsService.js
  services/usersService.js
  utils/auth.js
Labels: 멘토 리뷰 요청

#6 feature/sorting by query
  app.js
  controllers/cartsController.js
  controllers/index.js
  controllers/productsController.js
  controllers/usersController.js
  db/migrations/20230605024756_alter_products_table.sql
  db/migrations/20230605025135_alter_users_table.sql
  models/addressDao.js
  models/cartsDao.js
  models/productsDao.js
  routers/cartsRouter.js
  routers/index.js
  routers/productsRouter.js
  services/cartsService.js
  services/index.js
  services/productsService.js
Labels: Conflict 해결 요청

#8 :memo: [UPDATE]: code convention and fix minor typos
  controllers/usersController.js
  models/usersDao.js
  routers/index.js
  routers/usersRouter.js
  services/index.js
  services/usersService.js
Labels: 멘토 리뷰 요청

#9 :safety_vest: [FIX]: user authorization and use userId from req header
  controllers/cartsController.js
  controllers/usersController.js
  db/migrations/20230606091601_alter_shopping_cart_table.sql
  models/addressDao.js
  models/cartsDao.js
  models/usersDao.js
  routers/cartsRouter.js
  services/usersService.js
  utils/auth.js
Labels: 멘토 리뷰 요청

#11 Feature/create order
  controllers/cartsController.js
  controllers/index.js
  controllers/orderController.js
  db/migrations/20230606091601_alter_shopping_cart_table.sql
  db/migrations/20230607115935_alter_order_items_table.sql
  db/migrations/20230607122912_alter_orders_table.sql
  models/cartsDao.js
  models/orderDao.js
  routers/index.js
  routers/orderRouter.js
  services/cartsService.js
  services/index.js
  services/orderService.js
  utils/auth.js
Labels: 멘토 리뷰 요청, 수정 요청

#14 :bug: [FIX]: userId bug in get order query
  models/orderDao.js
Labels: 멘토 리뷰 요청

#12 Add: 유저의 CRUD 기능
  app.js
  controllers/usersController.js
  db/migrations/20230531063818_create_users_address_table.sql
  db/migrations/20230608042355__alter_users_address_table.sql
  db/migrations/20230608072030_alter_users_address_table2.sql
  models/index.js
  models/usersDao.js
  routers/usersRouter.js
  services/usersService.js
  utils/auth.js
Labels: 멘토 리뷰 요청
